- name: Advanced Issue Labeler
  uses: redhat-plumbers-in-action/advanced-issue-labeler@v3.2.4
  with:
    template-path:   .github/ISSUE_TEMPLATE/bug_report.yml

  id: [module]
  label:
    - name: ['[Module] Focus']
    - keys: ['[Module] Focus']
