# This .yaml was originally copied from the GitHub page of ATTWoWAddOn and modified to fit the Horizon Suite AddOn.

name: Log a Bug # Button Title
description: The entry is officially recorded on GitLab. It will be in the queue for the development team to review. #Button Description
labels: ["Logged"] #Automatically Applied Labels on Submission

body: # Overall Container
  - type: textarea  # Types: Dropdown, Input, TextArea
    id: description # Internal Reference
        attributes:
            label: "Description:"  # The question above the TextArea
            description: "Clearly and concisely describe the involved scenario."
            placeholder: "I see Blizzard Toasts for Quest Progress updates while Presence is toggled on."
        validations:
            required: true
   
  - type: textarea  
    id: expected 
        attributes:
            label: "Expected Behavior:" 
            description: "Clearly and concisely describe what you expected to happen."
            placeholder: "When Presence is enabled, I only see Quest Progress updates from Presence."
        validations:
            required: true
        
  - type: textarea 
    id: reproduce
        attributes:
            label: "To Reproduce:"
            description: "If applicable, list steps to reproduce the involved behavior\n1. Label any attached media with the specific step(s) they refer to.\n2I.E.:\n3 1. Go to '...' (Picture 1)\n4 2. Click on '....'.\n5 3. Scroll down to '...'\n6 4. See error as described."
            placeholder: "List steps here."
        validations:
            required: true
        
  - type: textarea 
    id: lua
        attributes:
            label: "LUA Errors:"
            description: "Include any LUA error messages (from BugSack or '/console scriptErrors 1')."
            placeholder: "Paste error logs here...
        
  - type: dropdown
    id: wowbranch
        attributes:
            label: "World of Warcraft:"
            description: "Branch:"
            options:
                - "Retail (Midnight)"
                - "Other (Classic, etc.)"
        validations:
            required: true
    
  - type: input
    id: wowversion
        attributes:
            label: "World of Warcraft:"
            description: "Version Number:"
            placeholder: "12.0.1"
        validations:
            required: true
            
  - type: dropdown
    id: horizonbranch
        attributes:
            label: "Horizon Suite:"
            description: "Branch:"
            options:
                - "Main"
                - "Beta"
        validations:
            required: true
            
  - type: input
    id: horizonversion
        attributes:
            label: "Horizon Suite:"
            description: "Version Number:"
            placeholder: "e.g., 3.11.5"
        validations:
            required: true

 - type: textarea
    id: extra
        attributes:
            label: "Extra:"
            description: "If applicable, provide any relevant information not covered by an above section."
            placeholder: "Thank you for all of your hard work!"