name: Feature request
description: Suggest a new capability
body:
- type: textarea
  id: name_1
  attributes:
    label: Name
- type: checkboxes
  attributes:
    label: Name-1
    options:
      - label: 'Name'
      - label: 'Name-2'
