# GitHub Documentation can be found at: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Feature request
description: Suggest a new capability

body:
                    
      - type: markdown
        attributes:
              value: "Please be clear and succinct, do not use whole sentences for the title."

              
      - type: textarea
        id: current
        attributes:
              label: Description
      - type: markdown
        attributes:
              value: "Please avoid the use of third person and the past tense (I, me, did, had, etc.)"

      - type: textarea
        id: expected
        attributes:
              label: Expected Behaviour

      - type: textarea
        id: reproduce
        attributes:
              label: To Reproduce


      - type: markdown
        attributes:
              value: "### Please apply the following! <br> "
      - type: markdown
        attributes:
              value: "### <br> --- Type --- <br>"
      - type: markdown
        attributes:
              value: "**Enhancement**"
      - type: markdown
        attributes:
              value: "### <br> --- Labels --- <br>"
      - type: markdown
        attributes:
              value: "**Module(s)** <br> **Priority**"
