# GitHub Documentation can be found at: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Make a Request💡
description: A request, idea, or new functionality.

body:
                    
      - type: markdown
        attributes:
              value: "## Lack of Current Function"

              
      - type: textarea
        id: current
        attributes:
              label: "_"
              placeholder: "Please write in the present tense without the use of first-person."
